services:
  api-gateway:
    build: .
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "4004:4004"
    networks:
      - internal
    environment:
      AUTH_SERVICE_URL: http://auth-service:4005
      JWT_SECRET: 8f4c1e4b7d0f6a8b2c5d9e1f4a7b8c0d1234567890abcdef

networks:
  internal:
    external: true