services:
  api-gateway:
    build:
      context: ..
      dockerfile: api-gateway/Dockerfile
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "4004:4004"
    networks:
      - internal
    environment:
      AUTH_SERVICE_URL: http://auth-service:4005
      JWT_SECRET: cGF0aWVudC1tYW5hZ2VtZW50LWp3dC1zZWNyZXQtaGFyaXByYWRhcDA5LTIwMjQ=

networks:
  internal:
    external: true