services:
  api-gateway:
    build: .
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "4004:4004"
    networks:
      - internal
    environment:
      AUTH_SERVICE_URL: http://auth-service:4005

networks:
  internal:
    external: true