spring.application.name=diagnosis-service

server.port=4009

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/diagnosis_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=never