server:
  port: 4004

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0

        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: doctor-service-route
          uri: http://doctor-service:4006
          predicates:
            - Path=/api/doctors/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: appointment-service-route
          uri: http://appointment-service:4007
          predicates:
            - Path=/api/appointments/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: billing-service-route
          uri: http://billing-service:4001
          predicates:
            - Path=/api/bills/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: analytics-service-route
          uri: http://analytics-service:4002
          predicates:
            - Path=/api/analytics/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: nurse-service-route
          uri: http://nurse-service:4008
          predicates:
            - Path=/api/nurses/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: diagnosis-service-route
          uri: http://diagnosis-service:4009
          predicates:
            - Path=/api/diagnoses/**
          filters:
            - StripPrefix=1
            - JwtValidation

auth:
  service:
    url: http://auth-service:4005

jwt:
  secret: cGF0aWVudC1tYW5hZ2VtZW50LWp3dC1zZWNyZXQtaGFyaXByYWRhcDA5LTIwMjQ=

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info

logging:
  level:
    org.springframework.cloud.gateway: DEBUG