apiVersion: apps/v1
kind: Deployment
metadata:
  name: nurse-service
  namespace: patient-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nurse-service
  template:
    metadata:
      labels:
        app: nurse-service
    spec:
      containers:
        - name: nurse-service
          image: haripradap09/nurse-service:1
          ports:
            - containerPort: 4008
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NURSE_DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
          resources:
            requests:
              memory: 256Mi
              cpu: 150m
            limits:
              memory: 384Mi
              cpu: 300m