apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: patient-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: haripradap09/analytics-service:1
          ports:
            - containerPort: 4002
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: "analytics-group"
            - name: SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET
              value: "earliest"
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "384Mi"
              cpu: "300m"
