apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: patient-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: haripradap09/api-gateway:1
          ports:
            - containerPort: 4004

          env:
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:4005"

          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "400Mi"
              cpu: "400m"