# HOW WE READ THIS FROM YOUR CODE:
# application.properties: server.port=4005   → containerPort: 4005
# Dockerfile: EXPOSE 4000  ← BUG in your code (copies wrong jar too!)
# We trust application.properties over Dockerfile when they conflict
# TODO: Fix auth-service Dockerfile:
#   1. Change EXPOSE 4000 to EXPOSE 4005
#   2. Change COPY doctor-svc jar to auth-service jar
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: patient-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: haripradap09/auth-service:1
          ports:
            - containerPort: 4005
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "400Mi"
              cpu: "300m"
