apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  namespace: patient-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        - name: appointment-service
          image: haripradap09/appointment-service:1
          ports:
            - containerPort: 4007
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "384Mi"
              cpu: "300m"
