spring.application.name=billing-service

server.port=4001
grpc.server.port=9003

spring.datasource.url=jdbc:postgresql://localhost:5002/billing_db
spring.datasource.username=admin_user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=never

spring.kafka.bootstrap-servers=localhost:9092

logging.level.root=INFO