spring.application.name=doctor-svc
server.port=4006

spring.datasource.url=jdbc:postgresql://localhost:5006/doctor_db
spring.datasource.username=admin_user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never

spring.kafka.bootstrap-servers=kafka:9092