services:

  doctor-db:
    image: postgres:17
    container_name: doctor-service-db
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: doctor_db
    ports:
      - "5006:5432"
    volumes:
      - doctor_db_data:/var/lib/postgresql/data
    networks:
      - internal

  doctor-service:
    build: .
    image: doctor-service:latest
    container_name: doctor-service
    depends_on:
      - doctor-db
    ports:
      - "4006:4006"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://doctor-db:5432/doctor_db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: never

      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - internal

networks:
  internal:
    external: true

volumes:
  doctor_db_data: