spring.application.name=appointment-service

server.port=4007

spring.datasource.url=jdbc:postgresql://localhost:5007/appointment_db
spring.datasource.username=admin_user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never

spring.kafka.bootstrap-servers=localhost:9092

logging.level.root=INFO