spring.application.name=appointment-service

server.port=4007

spring.datasource.url=jdbc:postgresql://localhost:5007/appointment_db
spring.datasource.username=admin_user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never

spring.kafka.bootstrap-servers=localhost:9092

grpc.client.patient-service.address=static://${PATIENT_SERVICE_HOST}:${PATIENT_SERVICE_GRPC_PORT}
grpc.client.patient-service.negotiationType=plaintext

grpc.client.doctor-service.address=static://${DOCTOR_SERVICE_HOST}:${DOCTOR_SERVICE_GRPC_PORT}
grpc.client.doctor-service.negotiationType=plaintext
logging.level.root=INFO