services:
  inventory-db:
    image: postgres:17
    container_name: inventory-service-db

    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory_db

    ports:
      - "5011:5432"

    volumes:
      - inventory_db_data:/var/lib/postgresql/data

    networks:
      - internal

  inventory-service:
    build:
      context: ..
      dockerfile: inventory-service/Dockerfile

    image: inventory-service:latest
    container_name: inventory-service

    depends_on:
      - inventory-db

    ports:
      - "4011:4011"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory-db:5432/inventory_db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: never

      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

    networks:
      - internal

networks:
  internal:
    external: true

volumes:
  inventory_db_data: